### ISSUE TITLE
Make `mdless` works as a symlink instead of hardlink

### ISSUE THREAD

**Issue by FollieHiyuki** [swsnr/mdcat#234]
I think it is more intuitive to have `mdless` works as a symlink of `mdcat`. A hard link wastes twice the disk space on the user machine.

**Comment by swsnr** [comment]
Why do you think so? I believe hard links consume almost no space.

**Comment by swsnr** [comment]
In any case, mdcat does not install a hardlink by itself. You're free to use a symlink if you like, so I think there's nothing for me to do here.
