### ISSUE TITLE
enhancement: sixel graphics support.

### ISSUE THREAD

**Issue by dan-da** [swsnr/mdcat#270]
Any plans to support sixel graphics?   Many terminals already support it.  See:
https://www.arewesixelyet.com/

VTE has sixel support now, although it is not built by default, and not yet included in any distros.  See:
https://gitlab.gnome.org/GNOME/vte/-/issues/253#note_886802

xfce4-terminal supports it, if present in vte.  See:
* https://gitlab.xfce.org/apps/xfce4-terminal/-/issues/76
* https://gitlab.xfce.org/apps/xfce4-terminal/-/issues/278

yazi, a cool, rusty cli terminal supports sixel, and would integrate nicely with mdcat:
https://github.com/sxyazi/yazi

**Comment by swsnr** [comment]
There are no such plans, and I will not add this myself.  All terminals I care support other image formats already, and I do not use yazi.

I'm closing this issue because it's not actionable to me.

Pull requests are welcome.
