### ISSUE TITLE
Option to justify normal paragraphs and center headers

### ISSUE THREAD

**Issue by Doroszewski** [swsnr/mdcat#271]
The `--columns` switch already allows the user to limit the width of the output, thus avoiding lines too long to be practical for reading.

I think it would be useful to provide the user with the most “easy on the eye” experience possible by adding an option to justify normal paragraphs (just like the usual Linux implementation of `man` does), i.e., their all lines but the last one.

I would also prefer to have headings rendered differently as an option:
* 2nd level and 3rd level: bold, centered, underlined adequately (with [kitty's underline protocol](https://sw.kovidgoyal.net/kitty/underlines/) or by adding a line width `=` or `-` beneath the given header);
* lower levels: probably aligned to the left, no dots before them, bold and underline for 4rd, only bold or undeline for 5th (I don't know what for the 6th one).

The current implementation makes the lower levels more visible, as they are closer to the center and prefixed by more “decorations” (i.e., dots).

Would it be possible to implement these?

I could try to implement them myself if I only knew Rust… However, I don't want to create yet another application like this from ground up.

<details>
<summary>(I had not noticed the `--columns` option until I was well into writing a feature request. Here's what I originally wrote, unfinished, just for information.)</summary>
Currently, `mdcat` renders “fancier” features of Markdown well: images, code blocks, etc. Simple text looks a lot like its source code, however. Be it a scientific paper, a manual or a note for oneself, the output is not so ergonomic: the lines are as long as wide is the terminal window. This is not easy to read; there's a reason web trends moved towards fixed-width layouts for content that's meant to be read. (Even the description box I'm filling right now is not as wide as it could be).

I think it would be good for `mdcat` to implement an “easy on the eye” mode, where:
* the width of the whole output would be limited (to 80 columns by default or to the amount specified by an option);
* paragraphs (i.e., their all lines but the last one) would be justified;
* 2nd-level and 3-level headers would be centered and underlined with two or one line respectively (if applicable, see [kitty's underline feature](https://sw.kovidgoyal.net/kitty/underlines/));
</details>

**Comment by swsnr** [comment]
I have no intention to change the style myself, but please do feel free to open a pull request with proposed changes to the styles.

I am closing this issue though, because it's not actionable to me.
