### ISSUE TITLE
Feature request: word wrapping

### ISSUE THREAD

**Issue by sam-artuso** [swsnr/mdcat#278]
Would be nice if mdcat could word-wrap markdown documents?

**Comment by maxim-uvarov** [comment]
@sam-artuso, have you tried the `--columns` flag? 
or do you mean splitting words like?

```
Officia tempor tempor dol-
ore aute laborum. Tempor do-
lore aute, laborum qui. La-
borum qui cillum, commodo.
```

**Comment by swsnr** [comment]
mdcat does word wrapping already, so I don't see what's actionable here. Closing.
