### ISSUE TITLE
2.2.0 release build failed

### ISSUE THREAD

**Issue by chenrui333** [swsnr/mdcat#284]
👋 looks like 2.2.0 release build failed, raise this issue for awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/177258

**Comment by swsnr** [comment]
I know, but I haven't found motivation to fix it.  Does it affect Homebrew?  I thought homebrew builds from source and doesn't use upstream binaries?

**Comment by chenrui333** [comment]
Thanks @swsnr!
