### ISSUE TITLE
Image does not display when called with an <img> tag, Line breaks with <br /> tag

### ISSUE THREAD

**Issue by relma2** [swsnr/mdcat#292]
I have a markdown file that looks like this:
```
**Text here** <br />
<img src="/path/to/image" width="80%">
```
And the image file does not display, because it is not using the Markdown-accepted image syntax, rather it is using the **<img>** HTML tag. The img tag displays verbatim.
---
Similarly, line breaks done with the `<br />` HTML Tag do not render as an actual line break, and instead display verbatim.

![image](https://github.com/user-attachments/assets/e2ecc205-d633-4bf1-860b-1417476e7aca)

Terminal: kitty
OS: EndeavourOS

Please inform me if I need to provide any other system information.

**Comment by swsnr** [comment]
See #3

**Comment by swsnr** [comment]
See also <https://github.com/swsnr/mdcat/blob/main/mdcat.1.adoc#commonmark-support-and-extensions>; please do read the manpage.
