### ISSUE TITLE
Support for images in Ghostty

### ISSUE THREAD

**Issue by mattrobenolt** [swsnr/mdcat#299]
This software worked fine if I forced it to `TERM=xterm-kitty` to get through the feature detection, but [Ghostty](https://mitchellh.com/ghostty) fully supports the kitty graphics protocol at minimum.

I'm not sure off hand if it could support jump marks, I'd have to experiment a bit.

But the following are appropriate for identifying Ghostty:

```
TERM_PROGRAM=ghostty
TERM=xterm-ghostty
```

I can share the whole terminfo if you'd like, but seems your detection is purely based on TERM and TERM_PROGRAM rather then querying the terminfo database.

**Comment by swsnr** [comment]
![Screenshot_20241112-185104](https://github.com/user-attachments/assets/4300b854-2d52-44d4-b8b7-1e1c4f4aacac)

Please understand that I am not inclined to add support for a proprietary terminal emulator in my own free time.

Feel free to open this ticket again should this thing really become open source, but this weird closed beta thing, the entitlement and the marketing lingo in their writing ("technical philanthropy", really?), and the exaggerated claims left me with such a bad impression of the whole project that it's exceedingly unlikely I'll ever add support for it.  

You're free to make a merge request, but if I need to spend more than a few moments to review it its unlikely Im going to merge it.

I'm sorry.

**Comment by mattrobenolt** [comment]
> Please understand that I am not inclined to add support for a proprietary terminal emulator in my own free time.

Yeah, of course, entirely understood and didn't have expectations here. Mostly just searched to see if it worked, and there wasn't an existing issue about it.

> You're free to make a merge request, but if I need to spend more than a few moments to review it its unlikely I'm going to merge it.

I'll give it a go, it looks pretty trivial.

> I'm sorry.

Don't feel sorry, truly, it's your software, like you said, in your own free time. I totally understand and respect that. I am simply a user who likes both mdcat and Ghostty. I worked around the current lack of support by doing `TERM=xterm-kitty mdcat`, so it's not a huge deal breaker for me. Don't feel pressured either way.

**Comment by mattrobenolt** [comment]
I've tossed up #300, but I truly understand if you don't want to merge. I'd appreciate it, but don't feel pressured.

I did build, wrote passing tests, and confirmed it works correctly for me within Ghostty.
