### ISSUE TITLE
Figure out what to do with HTML

### ISSUE THREAD

**Issue by swsnr** [swsnr/mdcat#3]

**Comment by PerBothner** [comment]
As mentioned in my comment to issue #12, [DomTerm ](https://domterm.org) has an escape sequence for handlng inline html, which makes this issue trivial.

**Comment by lunaryorn** [comment]
@PerBothner Thanks, that's very cool, but we'll still need to figure out how to support other terminal emulators.  At least, we must limit the special DomTerm escape codes to DomTerm and not use them on other emulators.  

Is there a way to detect whether a program runs in DomTerm?  Some environment variable perhaps?

**Comment by PerBothner** [comment]
As I mentioned in issue #12, the quick-and-dirty (and probably good enough) way is to check for a `DOMTERM` environment variable.

For a more robust test, see [this discussion](http://domterm.org/Shell-prompts.html).

**Comment by lunaryorn** [comment]
@PerBothner Thanks, I read your comment there right after I wrote the answer 🙈

**Comment by rien333** [comment]
This feature would be handy to parse out comments, as most markdown viewers/converters do (e.g. pandoc).  If you're interested in filtering out (html) comments specifically I could open up a separate issue tho.

**Comment by geoff-codes** [comment]
Render it with [w3m](https://sourceforge.net/projects/w3m)?

**Comment by lunaryorn** [comment]
No.

**Comment by brandonkal** [comment]
I'm not sure what the aversion is to using `w3m -dump`. The w3m browser isn't even 2 MB and is available by default on many Linux distros. The Homebrew w3m doesn't have image support as far as I can tell though...

But if you don't want to render any html, it would be nice to at least handle the block below:
```
<p align="center">
  <img height="180" width="210" src="https://user-images.githubusercontent.com/1631044/61989571-aae27580-afff-11e9-8f8a-c9768ed7a6b8.png">
</p>
```
Centered images are often the only HTML in markdown documents such as the README.md of a project.

Then just print any other HTML as normal.

**Comment by lunaryorn** [comment]
I don't think w3m would work well, so I'll not do it myself.  You say it doesn't have image support so it wouldn't even fix the one case you're interested in would it?

But go ahead and make a pull request with a prototype implementation and we can try it and see whether it's a viable solution.

In any case it won't happen if you don't do it; that's why there's a "help wanted" label 🤷‍♀️

**Comment by MinerChAI** [comment]
> I'm not sure what the aversion is to using `w3m -dump`. The w3m browser isn't even 2 MB and is available by default on many Linux distros. The Homebrew w3m doesn't have image support as far as I can tell though...
> 
> But if you don't want to render any html, it would be nice to at least handle the block below:
> 
> ```
> <p align="center">
>   <img height="180" width="210" src="https://user-images.githubusercontent.com/1631044/61989571-aae27580-afff-11e9-8f8a-c9768ed7a6b8.png">
> </p>
> ```
> 
> Centered images are often the only HTML in markdown documents such as the README.md of a project. Blocks like the above are quite common in GitHub markdown files even though the align attribute has been deprecated since 1997.
> 
> Then just print any other HTML as normal.

w3m works only on Xorg and not with all terminal emulators

**Comment by norman-abramovitz** [comment]
I am wondering if conceptually using something like [html2text](https://github.com/aaronsw/html2text) or [html2markdown](https://github.com/baynezy/Html2Markdown/tree/master/src/Html2Markdown) would make some sense?

Yes, we would need to rewrite the code in rust, but would the concept work, of identifying the HTML block,  feed it to the converter, and then feed the output back into your markdown formatter. 

We can start small by processing some simple constructs at first.

**Comment by swsnr** [comment]
Closing this, because I don't intend to do anything about HTML any time soon.

Pull requests are welcome.
