### ISSUE TITLE
`mdcat` Crash Report

### ISSUE THREAD

**Issue by suvayu** [swsnr/mdcat#306]
`mdcat` crashed when I was looking at the `vcpkg` [README](https://github.com/user-attachments/files/17952915/README.md) distributed with Fedora.

```toml
"name" = "mdcat"
"operating_system" = "Fedora 41.0.0 (FortyOne) [64-bit]"
"crate_version" = "2.5.0"
"explanation" = """
Panic occurred in file '/home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pulldown-cmark-mdcat-2.5.0/src/render.rs' at line 946
"""
"cause" = 'Event InlineHtml(Borrowed("<br>")) impossible in state Stacked(StateStack { top_level: TopLevelAttrs { margin_before: Margin }, states: [] }, TableBlock)'
"method" = "Panic"
"backtrace" = """
   0:     0x55b8472ec037 - rust_begin_unwind
   1:     0x55b846b75243 - core::panicking::panic_fmt::hdc63834ffaaefae5
   2:     0x55b846c4f6a1 - pulldown_cmark_mdcat::render::write_event::hed03b16b2ac0fc09
   3:     0x55b846c33584 - pulldown_cmark_mdcat::push_tty::h1a765ccfb79a280c
   4:     0x55b846c2cab5 - mdcat::process_file::h6ade83acc5c51d65
   5:     0x55b846b8467c - core::iter::traits::iterator::Iterator::try_fold::h26219094e7092423
   6:     0x55b846b85524 - mdcat::main::h9b17d970b90c42a3
   7:     0x55b846b81e63 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1da4a46318cbc917
   8:     0x55b846b80e39 - std::rt::lang_start::{{closure}}::h143b8b0dc3a0cc8f
   9:     0x55b8472dd050 - std::rt::lang_start_internal::h3ed4fe7b2f419135
  10:     0x55b846b85785 - main
  11:     0x7fd3e4f29248 - __libc_start_call_main
  12:     0x7fd3e4f2930b - __libc_start_main@GLIBC_2.2.5
  13:     0x55b846b75a15 - _start
  14:                0x0 - <unresolved>
"""
```

**Comment by swsnr** [comment]
Support for tables is not complete, see #301

**Comment by suvayu** [comment]
Hi, since this is not planned, I would like to contribute a better error message and explanation.  Do you have any guidance where in the code base I should start?

**Comment by swsnr** [comment]
I'm sorry but I don't have time to guide you through the code. It's reasonably structured, and mostly documented; you should be able to navigate it on your own.

**Comment by swsnr** [comment]
That said, it's not quite likely that I'd accept a contribution which merely changes the error message.

Either improve table support to fix the crash, or hide the whole table support behind a dedicated command line flag.

**Comment by suvayu** [comment]
Okay, I'll try it myself.  My intention was to fix the crash and give a message that table is not supported, and it is unlikely to change.

I only filed this issue because there was a crash report suggesting I file an issue.  If I knew that this was due to lack of table support, which is unlikely to change, I wouldn't have.  So I'm trying to prevent other people like myself from filing future issues.
