### ISSUE TITLE
Image links are not links

### ISSUE THREAD

**Issue by afranke** [swsnr/mdcat#311]
I have a link image in my file like so:

```
[![Rust](https://upload.wikimedia.org/wikipedia/commons/d/d5/Rust_programming_language_black_logo.svg)](https://www.rust-lang.org/)
```

And the image displays in wezterm, but the mouse pointer doesn’t change when I hover over it and nothing happens when I click on it, as if the link was not there.

**Comment by swsnr** [comment]
Does it work in any other terminal which renders images? e.g. kitty?

**Comment by afranke** [comment]
No, it doesn’t work with kitty either.

**Comment by swsnr** [comment]
Does it work with any older release of mdcat?

**Comment by afranke** [comment]
I installed mdcat for the first time yesterday, so I can’t tell if it’s a regression.

**Comment by swsnr** [comment]
Then please do try older releases; you can find binaries attached to Github releases.

**Comment by swsnr** [comment]
So this probably never worked :shrug: There's a test case for images within links under `pulldown-cmark-mdcat/tests/markdown/samples/images.md`. Its output snapshot at `pulldown-cmark-mdcat/tests/snapshots/render/iterm2@samples-images.snap` looks superficially correct, so perhaps neither iterm nor kitty support images inside links?  Can you clarify this with the respective upstreams?

**Comment by swsnr** [comment]
I'm closing this issue, as I don't intend to address this any time soon.

Please reopen if you have talkedmto terminal up streams about whether this is a supported feature at all, or if you can provide a pull request to change how?mdcat does this.
