### ISSUE TITLE
Feature Request: Themes/color control

### ISSUE THREAD

**Issue by rien333** [swsnr/mdcat#48]
Any way to change the color output? By default, my html comments are green, which for longer comments makes them quite hard to read in my theme (which might be partly due to my theme being at fault; nonetheless, being able to change it from green could improve readability under some circumstances)

Themes would be a more general solution, but an option that allows for more fine-grained control of colors could also be handy. 

As a slight bonus, it would be neat if themeing would allow you to se text properties (e.g. disabling bold headers, making comments italic but the same color as regular text, etc).

**Comment by lunaryorn** [comment]
I think I’ll make mdcat use syntect themes for colouring and styling and add means to change the theme via env vars, like bat does it.  This would also simplify code a bit.

Would this work for you?

**Comment by rien333** [comment]
Sure it would!

**Comment by lunaryorn** [comment]
Great.

Note to self: Use appropriate markdown scopes for elements in rendered output; see [Markdown syntax definition](https://github.com/sublimehq/Packages/blob/master/Markdown/Markdown.sublime-syntax) for a list of possible scopes.

**Comment by lunaryorn** [comment]
We’ll also want to check COLORTERM for 24bit support and use ansi_colours to convert to 256 bit colours if the terminal doesn’t support true colours.

**Comment by swsnr** [comment]
Closing this, because I don't intend to do anything about this any time soon.  Some basic infrastructure exists, but as things stand I'm happy with the default colours, and won't change anything here.

Pull requests are welcome.

**Comment by cohml** [comment]
I would also majorly support this feature (but can't contribute code as I don't know rust - yet! 😅 ). With 2k stars to date I'm honestly suprised this hasn't been requested more often.

For example, I use iTerm2 with a pretty standard dark mode theme, and TOC links are nearly unreadable:

<img width="362" alt="image" src="https://github.com/swsnr/mdcat/assets/62400541/1206fd65-fa0b-40d6-b672-b1c255325357">

This one niggle aside, major love for `mdcat`! Definitely the best command line Markdown viewer around.

**Comment by David-Else** [comment]
Hi, I am very confused. The README shows different themes: 

> mdcat in [WezTerm](https://wezfurlong.org/wezterm/), with "One Light (base16)", "Gruvbox Light", and "Darcula (base16)" (from left to right)

and it says you can use syntect code highlighting:

> highlights code blocks with [syntect](https://github.com/trishume/syntect),

How do i select the general theme, and/or the code highlighting theme? In bat I use:
```
export BAT_THEME="Visual Studio Dark+"
```
Do I have to select it in the source code and compile myself? Thanks.

**Comment by swsnr** [comment]
You can't. The screenshot shows different themes of the terminal emulator, IE, you'd select these in reg Wezterm config.

mdcat does not support custom themes.

**Comment by David-Else** [comment]
@swsnr Thanks for the quick feedback. How about syntect code highlighting? I am also having a look at t https://github.com/Inlyne-Project/inlyne.

**Comment by swsnr** [comment]
mdcat uses a fixed set of colors for syntect highlighting.  There is no custom theme support in mdcat. Really. 😉
